name: "Build app and deploy to Azure"
on: [push]

jobs:
  build:
    name: 'Build .NET Core App'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout Code from Repository' 
        uses: actions/checkout@v2
      - name: 'Set up .NET Core 3.1.x'
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      - name: 'Publish a Release of the App'
        run: |
          cd src/
          dotnet publish -c Release --output './publish'
